# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: EducProj

on:
  push:
    branches: [ "main","EPMFARMATS-16932.Erik" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Setup Nuget
      uses: Nuget/setup-nuget@v1.0.5
    - name: Restore nuget packages
      run: nuget restore AutomationTeamProject.sln
    - name: Build
      run: dotnet build --no-restore
    - name: run API Tests
      if: always()
      run: packages\NUnit.ConsoleRunner.3.16.3\tools\nunit3-console.exe API\bin\Debug\API.exe
    - name: run UI Tests
      if: always()
      run: packages\NUnit.ConsoleRunner.3.16.3\tools\nunit3-console.exe UI\bin\Debug\UI.exe
